outdir: 'exps'
name: ''

# Dataset options
task: 'inverse'  # forward, inverse, or forward_inverse
dataset: 'helmholtz'
data_path: 'data/DiffPDE/helmholtz_test_hf'
data_offset: null
resolution: 128  # downsampled resolution, defaults to dataset resolution
max_size: null  # maximum number of samples to use, defaults to one epoch
batch_size: 8

# Model options
pkl_path: '__required__'
rbf_scale: 0.05

# Generation options
seed: 2022862047 #1995291328
init_latents: "rbf"  # rbf or white_noise
iterations: 500
sigma_min: 0.002
sigma_max: 80
rho: 7

# Loss options
observation: 
  - type: "sparse"
    loss_type: "l1"  # mse, l1, l2, or huber
    known_indices: [500, 500]
    normalize: true
  - type: "pde"
    loss_type: "huber"
    derivative_method: "finite_diff"
  - type: "fno"
    loss_type: "mse"
    normalize: true

# Guidance options
# guidance:
#   type: "dps"
#   weights: [0, 2000, 0, 0]
guidance:
  type: "daps"
  annealing:
    num_steps: 200
    sigma_max: 10
    sigma_min: 0.01
    sigma_final: 0
    rho: 7
  diffusion:
    num_steps: 5
    sigma_min: 0.001
    sigma_final: 0
    rho: 7
  langevin:
    num_steps: 10
    lr: 1.0e-4
    lr_min_ratio: 0.01
    lr_rho: 1
    eta: 0.1  # noise level
    tau: 0.001  # the inverse of observation importance
    weights: [0, 10, 0, 0]

# I/O-related
n_plots: 4  # number of samples to plot
n_process_steps: 10  # number of steps to plot process
wandb: "offline"
